name: "Setup"
description: "Setup environment"
inputs:
  runner:
    description: "The runner for the setup"
    required: true
    type: string
  target:
    description: "The target for Rust"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "Setup actions/checkout"
      uses: actions/checkout@v4

    # setup ubuntu dependencies
    - name: Setup Ubuntu dependencies
      if: inputs.runner == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl wget file libssl-dev libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev  patchelf

    # install llvm (for llvm-copy) on macos only. For cpp runtimes.
    - name: "Setup MacOS dependencies"
      if: inputs.runner == 'macos-latest'
      run: |
        brew update
        brew install llvm@17
        echo "$(brew --prefix llvm@17)/bin" >> $GITHUB_PATH

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: "Setup rust"
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt

    - name: Add rust target (macOS)
      if: inputs.runner == 'macos-latest'
      run: rustup target add aarch64-apple-darwin

    - name: Add rust target (Other)
      if: inputs.runner != 'macos-latest'
      run: rustup target add ${{ inputs.target }}
