name: "build"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# This is the example from the readme.
# On each push to the `main` branch it will create or update a GitHub build, build your app, and upload the artifacts to the build.

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux-x86_64
            target: x86_64-unknown-linux-gnu
            runner: ubuntu-20.04

          - name: macOS-universal
            target: universal-apple-darwin
            runner: macos-latest

          - name: Windows-x86_64
            target: x86_64-pc-windows-msvc
            runner: windows-latest

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: "Setup actions/checkout"
        uses: actions/checkout@v4

      # setup ubuntu dependencies
      - name: Setup Ubuntu dependencies
        if: matrix.runner == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl wget file libssl-dev libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev  patchelf

      # install llvm (for llvm-copy) on macos only. For cpp runtimes.
      - name: "Setup MacOS dependencies"
        if: matrix.runner == 'macos-latest'
        run: |
          brew update
          brew install llvm@17
          echo "$(brew --prefix llvm@17)/bin" >> $GITHUB_PATH

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Setup rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Add rust target (macOS)
        if: ${{ matrix.runner == 'macos-latest' }}
        run: rustup target add aarch64-apple-darwin

      - name: Add rust target (Other)
        if: ${{ matrix.runner != 'macos-latest' }}
        run: rustup target add ${{ matrix.target }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install GUI frontend dependencies
        run: cd edgen && pnpm install # change this to npm or pnpm depending on which one you use

      - uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_KEY }}
          RUSTFLAGS: "--cfg tokio_unstable"
        with:
          args: --target ${{ matrix.target }}
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          projectPath: ./edgen
