name: "CI"
on:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: "Setup actions/checkout"
        uses: actions/checkout@v4

      - name: "Setup-action"
        uses: ./.github/workflows/setup-action
        with:
          runner: ubuntu-20.04
          target: x86_64-unknown-linux-gnu

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
